# theme: jekyll-theme-cayman
title: sqlite_rx
description: Python Client and Server for SQLite database with Docker support
baseurl: "/sqlite_rx" # the subpath of your site, e.g. /blog
url: "https://aosingh.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

remote_theme: pmarsceill/just-the-docs
heading_anchors: true

aux_links:
  "sqlite_rx on github":
    - "//github.com/aosingh/sqlite_rx"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

nav_sort: case_sensitive # Capital letters sorted before lowercase

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/aosingh/sqlite_rx" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
